services:
  chrome:
    image: selenium/standalone-chrome:latest
    ports:
      - "4444:4444"
    shm_size: 2gb
    
  parser:
    build: ./bank-rates
    container_name: BankRateParser
    ports:
      - "8085:8085"
    depends_on:
      - db
      - chrome
    

  notify:
    build: ./grpc-notify
    container_name: grpc-notify
    ports:
      - "50051:50051"

  db:
    image: postgres:15
    container_name: postgres_db_parser
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: db
      POSTGRES_PASSWORD: db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always   

volumes:
  postgres_data:
