FROM golang:1.25.1-alpine

WORKDIR /app

# Копируем go.mod и go.sum
COPY go.mod go.sum ./
RUN go mod download

# Копируем весь исходный код
COPY . .

# Собираем бинарник
RUN go build -o main ./cmd/main.go

CMD ["./main", "--config=./config/local.yaml"]
